# Reporting the relative reporter ion abundances for peptides identified in the PSM table generated by FragPipe
# this chunk of code is useful for plotting TMT 16-plex data, but can be easily modified for other TMT multiplexing methods

library(tidyverse)
library(janitor)

psm <- read_tsv("./psm.tsv") %>% # import the PSM table from FragPipe output
    clean_names()

# keep the information of the reporter ion abundances and retention time for plotting
psm %>%
    dplyr::select(c(9, 40:55)) %>%
    gather(key = "channel", value = "signal", -retention) %>%
    ggplot(aes(x = retention / 60, y = signal, color = channel)) +
    geom_line() +
    guides(color = guide_legend(override.aes = list(size = 15)), size = "none") +
    labs(
        x = "Retention time (min)", y = "Relative reporter ion abundances",
        color = "Channel"
    ) +
    scale_y_continuous(labels = function(x) format(x, scientific = TRUE)) +
    facet_wrap(~channel, ncol = 4, scales = "free_y") +
    theme_bw() +
    theme(
        axis.text.x = element_text(size = 14),
        axis.text.y = element_text(size = 14),
        title = element_text(size = 20, face = "bold"),
        strip.text = element_text(size = 14, face = "bold"),
        legend.position = "bottom"
    )
